Start the CV evluation on NA12878 data for different read depth ...
 missComplete 
python train.py -b 1000 -em single -ds CV -da 0 -d na12878_300x -m UNet_CV -g 2  -mp missComplete
Using TensorFlow backend.
@ Setting randomness fixed ....
- Random seed set [DONE]!! (*not work for the GPU training)
[Genome]: ** Generate basic statistics, Depth-of-Coverage hist ... 
[Genome]: ** Cached 0.010000 Genome Depth-of-coverage statistics is [261.257355, 57.338917]
-- loading cache genome information done!
[BIN_DATA]:Background data [m=257.971919, std=85.249700]
[BIN_DATA]:Break point containing [m=184.481931, std=113.336110]
-- loading cache bin data information done!
	 * [Filtering]:Ignoring All-ZERO input in the Training dataset, Number is [88]
	 * [Filtering]:Ignoring ALL-ZERO input in the Testing set, Number is 59
BK=4042 / Total=8076
Traceback (most recent call last):
  File "train.py", line 386, in <module>
    globals()[args.model](dataPath, bk_dataPath, modelParamPath, "../experiment/model/", dataInfo)
  File "train.py", line 58, in UNet_CV
    params = load_modelParam(config.DATABASE["model_param"])
  File "/data/workspace/deepSV_1.0/code/model_hyperOpt.py", line 207, in load_modelParam
    with open(paramFile, "r") as f:
IOError: [Errno 2] No such file or directory: 'missComplete'

@ TRAIL 1 takes 6 seconds

